language: php

git:
  depth: 50

env:
  global:
    - CHECK_SECURITY=false
    - COVERAGE=false
    - LINT=false
    - NIGHTLY=false
    - UPDATE_CHECK_VERSION_TIMESTAMP_FILE=$HOME/.unicode-normalization/version-check-timestamp

matrix:
  include:
    - php: 7.0
    - php: 7.1
      env: LINT=true COVERAGE=true CHECK_SECURITY=true
    - php: 7.2
    - php: nightly
      env: NIGHTLY=true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
    - $HOME/.unicode-normalization
    - $HOME/vendor

install:
- env
- if [ -f $UPDATE_CHECK_VERSION_TIMESTAMP_FILE ]; then
    echo "Unicode Version Check Timestamp => found";
    cat $UPDATE_CHECK_VERSION_TIMESTAMP_FILE;
  else
    echo "Unicode Version Check Timestamp => missing";
  fi 
- if [[ ! $COVERAGE = true ]]; then
    phpenv config-rm xdebug.ini || true;
  fi
- travis_retry composer self-update
- composer diagnose || true
- if [[ $NIGHTLY = true ]]; then
    composer remove --dev friendsofphp/php-cs-fixer;
  fi
- travis_retry composer install --optimize-autoloader --no-interaction
- composer run:require-native-runtime
- composer check-platform-reqs
- composer validate

script:
- if [[ $LINT = true ]]; then
    composer run:cs-lint;
  fi
- if [[ $(( $TRAVIS_BUILD_NUMBER % 10 )) = 0 ]]; then
    composer -v run:test-all;
  elif [[ ! $COVERAGE = true ]]; then
    composer -v run:test;
  fi
- if [[ $COVERAGE = true ]]; then
    composer -v run:test-coverage;
  fi
- if [[ $CHECK_SECURITY = true ]]; then
    composer run:security-check-bugfix-for-travis;
  fi

sudo: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: VoM66eYXAsivxrIAFd8zVeuS+SPQQ/qyudTBNI7cibNq1tCqbOFxVwbqMDqQKrnaWBIU3lpDOIaxXAhEi/1V1wOoXvE50lRr6dLEuaMX3ZSNHSfPcdzFcafm+1l2GyNa+B0o2YuZhRKP414O/UOTVrdZSddXnifZBfMdDd2hPDermGWeGq2nauyJ9QbO31TvSow3rCIGM0NWsbFTxoRAk2mvfvZboUk/JWmnQoE/J+VYXYzILJvDSPUSEMnyIHehFLqewKoaB3P8cfC0qLSOMCyx2aHfQYofMJbHQenV6Se+UY5V6NfaFCb78pY5powArJbgHqE9JDbM4cEFBU+wkrX9cOOLhTLjLKzxJFDwy6zcAsjBV8f96/eWYTnW2Nmp0SrILrIteeqjVkyu00ac8jEBZcjzkcd/W0T0gWfYDHz67LyAUY7UnO6ZVY9q8dMGttzVabYeZIEuzBhPXakH56VwiY6bxjrhEnmOoHnxDkoB7iquVWsq8C1O2dMiydBI9KxozeF5GGA4QiS4NTMl9ORjq4TdiBEuhgJ5tzcxqQ6FGvQwydGjlWY40DiBOMiDz33pW9pg4Bc4bcHwbtT/hdt24DxlrL7fDQE3oMaifjLLuJxoINEohlKwbzNp2H9uK9YG/Zxy/5c3OS9xi5NH1ZB0uFkxlJRE7cIgkwlqZIc=

